name: CI/CD Pipeline for Airflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.sh'
      - 'requirements.txt'
      - 'airflow.cfg'
      - 'dags/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop nginx
            sudo cp -r ~/airflow/dags/* /home/ec2-user/airflow/dags/
            sudo cp -r ~/airflow/airflow.cfg /home/ec2-user/airflow/airflow.cfg
            sudo systemctl start nginx
